receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      load:

processors:
  resourcedetection:
    detectors: ["env", "system"]
    system:
      hostname_sources: ["os"]

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection]
      exporters: [logging]

