receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      load:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [logging]

