exporters:
  logging:

receivers:
  otlp:
    protocols:
      http:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
