exporters:
  logging:

receivers:
  otlp:
    protocols:
      http:

service:
  telemetry:
    logs:
      initial_fields:
        service: my-static-name
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
