exporters:
  logging:

receivers:
  otlp:
    protocols:
      http:

service:
  telemetry:
    logs:
      initial_fields:
        service: ${OT_SERVICE}
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
