receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning
    operators:
      - id: regex-parse
        type: regex_parser
        parse_from: body
        regex: 'Host=(?P<host>[^,]+), Type=(?P<type>[^\s]+)'
#  hostmetrics:
#    collection_interval: 5s
#    scrapers:
#      load:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
#    metrics:
#      receivers: [hostmetrics]
#      exporters: [logging]

