exporters:
  logging:
    loglevel: debug

receivers:
  prometheus_simple:
    endpoint: "0.0.0.0:8888"
  prometheus_simple/own:
    endpoint: "0.0.0.0:8889"

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8889
  pipelines:
    metrics:
      receivers: [prometheus_simple, prometheus_simple/own]
      exporters: [logging]

