exporters:
  logging:
    loglevel: debug

receivers:
  otlp:
    protocols:
      grpc:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging]

