version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  the-coffee-bar:
    image: public.ecr.aws/sumologic/the-coffee-bar:pythonAppsv0.2.1-ot1.10.1-0.28b1
    container_name: the-coffee-bar
    hostname: the-coffee-bar
    ports:
      - 8082:8082
    expose:
      - 8082
    command: ["opentelemetry-instrument", "the-coffee-bar",
              "--host=the-coffee-bar", "--port=8082", "--coffeemachine-host=the-coffee-machine",
              "--coffeemachine-port=8083", "--cashdesk-host=the-cashdesk", "--cashdesk-port=8084"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp_proto_http
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=the-coffee-bar
      - OTEL_PROPAGATORS=xray,tracecontext,baggage
  the-coffee-bar-frontend:
    image: public.ecr.aws/sumologic/the-coffee-bar:frontend-v0.1.3
    container_name: the-coffee-bar-frontend
    hostname: the-coffee-bar-frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    command: |
      /bin/bash -c "npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_RUM_SCRIPT_URL=https://rum.sumologic.com/sumologic-rum.js
      - REACT_APP_COFFEE_BAR_URL=http://localhost:8082/order
      - REACT_APP_SERVICE_NAME=the-coffee-bar-frontend
      - REACT_APP_COLLECTION_SOURCE_URL=$SUMOLOGIC_HTTP_TRACES_URL
      - REACT_APP_APPLICATION_NAME=tcb-local
      - REACT_APP_DEFAULT_ATTRIBUTES={"testKey":"testValue","testListKey":["1"]}
      - REACT_APP_PROPAGATION_CORS_URLS=[/^http:\/\/localhost:8082\/.*/,/^http:\/\/the-coffee-bar:8082\/.*/,]
      - REACT_APP_DROP_SINGLE_TRACES=false
  the-coffee-machine:
    image: public.ecr.aws/sumologic/the-coffee-bar:pythonAppsv0.2.1-ot1.10.1-0.28b1
    container_name: the-coffee-machine
    hostname: the-coffee-machine
    ports:
      - 8083:8083
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_machine.py",
              "--host=the-coffee-machine", "--port=8083", "--machine-svc-host=machine-svc",
              "--machine-svc-port=9090", "--spike-cron=1 * * * *", "--spike-duration=60", "--cpu-spike-processes=1"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp_proto_http
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=the-coffee-machine
  the-cashdesk:
    image: public.ecr.aws/sumologic/the-coffee-bar:pythonAppsv0.2.1-ot1.10.1-0.28b1
    container_name: the-cashdesk
    hostname: the-cashdesk
    ports:
      - 8084:8084
    command: ["opentelemetry-instrument", "python3", "src/bin/the_cashdesk.py",
              "--host=the-cashdesk", "--port=8084", "--calculator-host=calculator-svc", "--calculator-port=8090",
              "--connection-string=postgresql://account:account@postgres:5432/account"]
    environment:
      - OTEL_TRACES_EXPORTER=otlp_proto_http
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=the-cashdesk
  machine-svc:
    image: public.ecr.aws/sumologic/the-coffee-bar:rubyAppsv0.1.1-ot1.0.2-0.23.0-0.21.2
    container_name: machine-svc
    hostname: machine-svc
    ports:
      - 9090:9090
    command: ["ruby", "/app/lib/machine.rb"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=machine-svc
  coffee-svc:
    image: public.ecr.aws/sumologic/the-coffee-bar:rubyAppsv0.1.1-ot1.0.2-0.23.0-0.21.2
    container_name: coffee-svc
    hostname: coffee-svc
    ports:
      - 9091:9091
    command: ["ruby", "/app/lib/coffee.rb"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=coffee-svc
  water-svc:
    image: public.ecr.aws/sumologic/the-coffee-bar:rubyAppsv0.1.1-ot1.0.2-0.23.0-0.21.2
    container_name: water-svc
    hostname: water-svc
    ports:
      - 9092:9092
    command: ["ruby", "/app/lib/water.rb"]
    environment:
      - OTEL_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local,service.name=water-svc
  calculator-svc:
    image: public.ecr.aws/sumologic/the-coffee-bar:calculator-dotnet-1.2.0-1.0.0rc9
    container_name: calculator-svc
    hostname: calculator-svc
    command: ["dotnet", "dotnet-core-calculator-svc.dll", "http://calculator-svc:8090"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=application=tcb-local
      - OTEL_SERVICE_NAME=calculator-svc
    ports:
      - 8090:8090
  otelcol:
    image: public.ecr.aws/sumologic/sumologic-otel-collector:0.51.0-sumo-0
    container_name: otelcol
    hostname: otelcol
    command: ["--config=/etc/otel-collector-config_otlp.yaml"]
    volumes:
        - ./otelcol-config.yaml:/etc/otel-collector-config_otlp.yaml
    environment:
      - SUMOLOGIC_HTTP_TRACES_URL=$SUMOLOGIC_HTTP_TRACES_URL
    ports:
      - 4318:4318
    expose:
      - 4318
