receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      load:

processors:
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - system.cpu.load_average.1.*

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [filter]
      exporters: [logging]

