receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning
    operators:
      - id: regex-parse
        type: regex_parser
        parse_from: body
        regex: 'Host=(?P<host>[^,]+), Type=(?P<type>[^\s]+)'
  hostmetrics:
    collection_interval: 5s
    scrapers:
      load:

processors:
  filter:
    logs:
      exclude:
        match_type: regexp
        record_attributes:
          - key: host
            value: foo.*
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - system.cpu.load_average.1.*

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [filter]
      exporters: [logging]
    metrics:
      receivers: [hostmetrics]
      processors: [filter]
      exporters: [logging]
